### ISSUE TITLE
Support for multiple Directus storages

### ISSUE THREAD

**Issue by Guiqft** [Guiqft/directus-backup-endpoint#1]
We only accept `local` as [Directus storage](https://github.com/Guiqft/directus-backup-endpoint), the support and configuration for S3, GCS and Azure would be a great feature.

**Comment by hermesalvesbr** [comment]
But if the directus files are set to s3, won't it save from local to s3? 

https://docs.directus.io/self-hosted/config-options.html#s3-s3

**Comment by Guiqft** [comment]
Seems like [ServiceFiles.uploadOne](https://github.com/directus/directus/blob/0a5ff6d12a77deb5cdc2d740cc9d643ee44c692e/api/src/services/files.ts#L33) method just takes the storage name and automatic handles the upload following your `.env` config. 
I think I just needs to give a option to select the storage name and Directus takes care of the rest.
